### PR TITLE
179 fix avatar

### PR DESCRIPTION
**Pull request by Vedanth15**
### Description

Made changes to avatar's page

### Testing Directions

```
python manage.py migrate
python manage.py pull_seatgeek_data
python manage.py make_users
python manage.py runserver
```
Goto MyProfile and click on the avatar edit the avatar

### Checklist

- [x] I have written tests which have maintained/increased test coverage.
- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by mksavic** [comment]
@Vedanth15 I tried uploading a picture but it is not appearing at `http://127.0.0.1:8000/avatar/change/`:

Screen Shot 2019-11-25 at 3 43 05 PM
Screen Shot 2019-11-25 at 3 43 08 PM
Screen Shot 2019-11-25 at 3 43 11 PM

**Comment by Vedanth15** [comment]
@mksavic  Made changes, can you review it again

**Comment by mksavic** [comment]
@Vedanth15 Still have the same issue.

I tried the following two cat pictures:

cat_1
cat_2
Screen Shot 2019-11-25 at 6 13 09 PM
Screen Shot 2019-11-25 at 6 13 21 PM
Screen Shot 2019-11-25 at 6 13 11 PM

**Comment by Vedanth15** [comment]
@mksavic Please review it one last time lol

**Pull request merged**
