### PR TITLE
PR for #267: Manage Account Settings Front End

### PR DESCRIPTION
**Pull request by Vedanth15**
### Description

Made UI development to Manage Account Settings and added an image to Homepage so that it doesn't look bland

### Testing Directions

```
python manage.py migrate
python manage.py pull_seatgeek_data
python manage.py make_users
python manage.py runserver
```

Goto Settings tab and look at the UI, on the homepage a picture is added

### Checklist

- [x] I have written tests which have maintained/increased test coverage.
- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by vmoros** [comment]
I agree with Mel's requested changes. Also why use a pic of a bus stop?

**Comment by Vedanth15** [comment]
@vmoros I couldn't find any other better pictures so I used what I could find

**Comment by Vedanth15** [comment]
@mksavic I'll make the changes you requested, but I didn't get what you meant by ' It would be nice to use the same theme we have with the dancing grandmas. I think there was more pics in that library.' Do you want me to use another picture or just resize the existing image?

**Comment by Vedanth15** [comment]
@vmoros @mksavic  Made the changes requested.

**Pull request merged**
