### PR TITLE
Manage account settings

### PR DESCRIPTION
**Pull request by kavinshah**
### Description

Added ability to change user details entered during signup

### Testing Directions

```
python manage.py makemigrations
python manage.py migrate
python manage.py pull_seatgeek_data
python manage.py make_users
```

1.  signup as a user
2.  goto settings tab
3.  change settings and click save button. Check if a success message shows up. Also, check if the details are changed when you revisit the settings page after saving.
4. Goto settings tab, change a few details. click reset and check if all the changes are gone and form is reloaded with all original details
5. Click change password and enter email id where asked on new a page. Change the password and login again using the new password
6. Click on change email and add a new email address and verify it. You should be able to login using the new email address.
7. Showdown you computer and go back to sleep.

### Miscellaneous Comments

You don't need to remove your email address to be able to add a new email address.

img 1

send

img 3

### Checklist

- [X] I have written tests which have maintained/increased test coverage.
- [X] I ran `git merge develop` before submitting this PR.
- [X] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [X] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by jawooson** [comment]
Much of it LGTM. I'm testing now and it seems that the ALLAUTH functionality is throwing a few errors. 

###ALLAUTH Bugs
1. I tried adding a new email before removing the current one, and I received a ```SMTPAuthenticationError``` 
2. After removing the current email, I wanted to send a verification link to the new email, and the same error happened. 
3. After doing all this I tired changing password and the same error occurred. I assume that's because no email is verified for the acct? 

###Session 
1. When going to the setting tabs, a session history is provided. Can we get rid of that?

**Comment by kavinshah** [comment]
> Much of it LGTM. I'm testing now and it seems that the ALLAUTH functionality is throwing a few errors.
> 
> ### ALLAUTH Bugs
> 1. I tried adding a new email before removing the current one, and I received a `SMTPAuthenticationError`
> 2. After removing the current email, I wanted to send a verification link to the new email, and the same error happened.
> 3. After doing all this I tired changing password and the same error occurred. I assume that's because no email is verified for the acct?
> 
> ### Session
> 1. When going to the setting tabs, a session history is provided. Can we get rid of that?
>    

1. not sure of point 1-3. Refer the screenshot below for clarity.

send

2. Fixed the issue with session messages

@jawooson

**Comment by kavinshah** [comment]
> 
> 
> LGTM but I still see the messages about the session history that Jason asked to be removed
> 
> image

yeah that's correct. fixed it.

**Comment by mksavic** [comment]
Found a bug outlined in #264.

**Comment by mksavic** [comment]
@kavinshah 

You have a backend bug that causes ShowUp to break. I can't pull this in until it's fixed.

ScreenRecording2019-12-04at42546

**Comment by kavinshah** [comment]
> @kavinshah
> 
> You have a backend bug that causes ShowUp to break. I can't pull this in until it's fixed.
> 
> ScreenRecording2019-12-04at42546

made changes to views.user to take in correct email address. It was basically taking in a non existent email address instead to taking in email id from user model. the bug has been resolved now.

**Comment by mksavic** [comment]
@kavinshah Plz fix #264 since this PR did not make the Libra sprint.

**Comment by kavinshah** [comment]
> @kavinshah Plz fix #264 since this PR did not make the Libra sprint.

https://github.com/gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities/issues/264#issuecomment-561876202

**Pull request merged**
