### PR TITLE
Improved UI for matches

### PR DESCRIPTION
**Pull request by Vedanth15**
### Description

Improved the UI for the Matches Page.

### Testing Directions

```
python manage.py migrate
python manage.py pull_seatgeek_data
python manage.py make_users
```

Make 2 users or more interested/going to an event. Make a match between 2 users, they should be appearing on Matches tab. Now the matches.html looks something similar to home.html. Also added Message, User Profile link in matches.

### Checklist

- [x] I have written tests which have maintained/increased test coverage.
- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by Vedanth15** [comment]
@mksavic I don't know if this is good enough. Please look at it and leave any comments.

**Comment by Vedanth15** [comment]
@mksavic 
I think ik why collapses are buggy, and also i think you are right. For every event a match would be better. I will update it.

**Comment by Vedanth15** [comment]
@mksavic I fixed the bug and also changed the template of matches. Made the changes you requested can you take a look at it and lemme know if anything is wrong.

**Comment by mksavic** [comment]
@Vedanth15 hey! this is awesome, it turned out way better than i imagined. thank you so much! i'm going to pull in develop and fix the migrations along with displaying "no matches available" on the empty screen. then i'll accept. thanks!

**Comment by vmoros** [comment]
@Vedanth15, it looks super nice but I think there's a bug. I gave my user 3 matches for event A and 1 match for event B. If I expand the details for event B and then expand the details for event A, only 1 match is shown for event A but there should be 3. It's hard to explain, please watch this gif:
> matches bug

@mksavic, I don't know if this is the same bug that you mentioned earlier because the link to your gif doesn't work.

**Comment by mksavic** [comment]
@vmoros it was kind of a similar bug but not really. i didn't have this issue. idk

**Comment by Vedanth15** [comment]
@vmoros I fixed the bug. Thanks for pointing it out.

**Comment by vmoros** [comment]
Leprosy Gangrene Tonsillitis Melanoma

**Pull request merged**
