### PR TITLE
PR for #177: Media/Static File Permanence

### PR DESCRIPTION
**Pull request by mksavic**
### Description

Fix the media/static file permanence problem.

### Testing Directions

```
./setup
python manage.py runserver
```

We are hosting this branch on https://showup-nyc-media.herokuapp.com/ to demonstrate that these changes work.

1.  Navigate to https://showup-nyc-media.herokuapp.com/.
1.  Log in as `vm1564@nyu.edu`. I uploaded a profile photo at 12/09/2019 @ 09:40pm. See that it's still there.
1.  Log in as `vm1564+1@nyu.edu`. I uploaded a profile photo at 12/09/2019 @ 09:40pm. See that it's still there.

### Miscellaneous Comments

*   @jawooson and I verified that that photos are uploaded to the AWS S3 bucket.
*   Sometimes the Travis CI - Branch build fails even though the Travis CI - Pull Request build passes. I think it has something with how fast they're running the builds so if your build ever fails in the future just restart the build and it might resolve the issue.

### Checklist

- [x] I have written tests which have maintained/increased test coverage.
- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by mksavic** [comment]
@vmoros 

If you have a chance can you take a look at this, the fonts aren't working and Jason and I don't know what else to try anymore.

We tried this:
*   https://stackoverflow.com/questions/25577597/custom-fonts-on-heroku-with-django-python
*   http://schock.net/articles/2013/07/03/hosting-web-fonts-on-a-cdn-youre-going-to-need-some-cors/

**Comment by vmoros** [comment]
@mksavic the first link is related to fonts that are loaded from a CDN. We are getting FontAwesome from a CDN but that's only for the thumbs up and down and some other arrows somewhere. Our main fonts are stored in our static files.

The second link looks promising though because in my console, I see CORS errors: 
image

This link works, which tells me that the problem is not that the fonts are missing: https://showupnyc.s3.amazonaws.com/static/theme/fonts/HK%20Grotesk%20Pro/HKGroteskPro-Regular.woff2

Also the styling is not completely messed up, which means that our theme's CSS is working, and that's stored in the same place as the fonts, so some static files are working.

So all of this is evidence that CORS is the problem. Unfortunately, I've never dealt with that and I know nothing about it. [This page](https://coderwall.com/p/ub8zug/serving-web-fonts-via-aws-s3-and-cloudfront) has advice that's very similar but slightly different from the advice in your second link. Remember to replace `your-site.com` with our real URL or even with `*` to allow any origin.

I noticed that the font of our logo is working correctly, and that's coming from Google fonts. So one option is to look at the fonts at https://fonts.google.com/ and choose one that we like and use that instead of the font we've been using in our theme.

**Comment by jawooson** [comment]
@vmoros Thanks for the input! Super helpful. I changed the CORS config to what you linked to. 

It wasn't working after I changed the config, but its because the fonts were cached. When I open an incognito browser, the fonts were correct. 

Everything should be good to go with this!

media_static

**Comment by mksavic** [comment]
The CORS configuration is as follows for those who are curious:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
</CORSRule>
</CORSConfiguration>
```

**Comment by mksavic** [comment]
Bucket Policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Allow All",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::showupnyc/*"
        }
    ]
}
```

**Comment by mksavic** [comment]
Access Control List:

Screen Shot 2019-12-10 at 2 42 04 PM

**Comment by mksavic** [comment]
Block public access:

Screen Shot 2019-12-10 at 2 45 11 PM

**Pull request merged**
