### PR TITLE
PR for #234: fix interested/going override bug

### PR DESCRIPTION
**Pull request by mksavic**
### Description

I forgot to write code that joins two squads' interested/going events. The logic is as follows:

* If an event is marked as going for either squad, the resulting squad will have that event marked as going.
* If an event is marked as interested for either squad (not going in either), the resulting squad will have that event marked as interested.

### Testing Directions

```
./setup
python manage.py runserver
```

Please see `showup/tests.py` for the edge cases I wrote. I wrote comments there so it should be easy to follow along and test for yourself on the UI. Note that we have an invariant which states that the squad with the smaller squad id remains.

### Checklist

- [x] I have written tests which have maintained/increased test coverage.
- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by mksavic** [comment]
@kavinshah Can you please tell me who was in each squad, what their squad ids were, and who you were logged in as so I can replicate the error? Thanks.

**Comment by kavinshah** [comment]
User 1,2 in a squad
User 3 in a squad of its own.
User 1 invited user 3 to join the squad.
Rest as follows
@mksavic

**Comment by mksavic** [comment]
@kavinshah 

Ok, this is #196. After looking at it I think I know what the issue is. Once you accept the squad request, and click on "My Squad" the url is not updated in `header.html` so the link contains the old squad id. If you refresh the page and click on "My Squad" the link works. I'm 99% sure this is the issue.

**Comment by mksavic** [comment]
I am trying to fix the issue Kavin highlighted right now.

**Comment by mksavic** [comment]
@kavinshah 

Ok, I fixed it. An `ConnectionResetError: [Errno 54] Connection reset by peer` error is thrown in the console when running `python manage.py runserver` but whatever 🤷‍♀️.

**Comment by Vedanth15** [comment]
@mksavic Can you set the timeout to `5` instead of `10`. I'm positive that setting it to `10` doesn't always fix this bug in prod.

**Comment by mksavic** [comment]
@Vedanth15 for little changes like that it's easier for you just to change it instead of waiting for me to see it and fix it. done tho.

**Comment by Vedanth15** [comment]
@mksavic  Alrighty, I was at work so couldn't make changes. Will do next time.

**Pull request merged**
