### PR TITLE
75 interested going

### PR DESCRIPTION
**Pull request by kavinshah**
### Description

Made click events on going and interested for events mutually exclusive.

### Testing Directions

```
python manage.py makemigrations
python manage.py migrate
python manage.py pull_seatgeek_data
```

1.  Click on any event and mark it as interested
2. Mark the same events as going and check the home or profile tab to see if that event is moved from interested stack to going stack.
3. Do the same for an event marked going and change to interested.
4. Check if the color of the interested/going button change to red and back to teal when we select/unselect going/interested options respectively.

### Miscellaneous Comments
None

### Checklist

- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by mksavic** [comment]
@vmoros It would nice to get your feedback on this since I don't entirely see how the Swipe model could be affected by this.

**Comment by vmoros** [comment]
I'll review this tonight

**Comment by vmoros** [comment]
Switching an event from Interested to Going works well but there seems to be a bug with removing an event from the list that it's already in. If I'm marked as Interested in an event, then the button correctly changes to Not Interested. But then when I click Not Interested, it should change back to Interested but it doesn't. See the gif below:
bug

Regarding the new Swipe model, the changes here won't affect or be affected by that.

**Comment by mksavic** [comment]
@vmoros Hmmm I kind of see what you're saying. Sometimes the buttons are finnicky. Have you tried clicking it, and when it doesn't change color, refreshed the page? It actually does update the value, however the color sometimes doesn't automatically change. Kind of similar to the issue we have with swiping.

**Comment by kavinshah** [comment]
> @vmoros Hmmm I kind of see what you're saying. Sometimes the buttons are finnicky. Have you tried clicking it, and when it doesn't change color, refreshed the page? It actually does update the value, however the color sometimes doesn't automatically change. Kind of similar to the issue we have with swiping.

I had this issue during development too. Not sure what exactly is the root cause for it, template or backend?

**Comment by vmoros** [comment]
I'm willing to accept it with this minor bug and we'll fix the bug later. Should we do that?

**Pull request merged**
