### PR TITLE
PR for #194: Unmark Events on Homepage

### PR DESCRIPTION
**Pull request by Vedanth15**
### Description

Added the ability to unmark an event throught user page.

### Testing Directions

```
python manage.py migrate
python manage.py pull_seatgeek_data
python manage.py make_users
python manage.py collectstatic
python manage.py runserver
```

1. Create a user account and mark the user Interested/Going to events.
2. Navigate to `/u/uid` and click on the collapse, Collapse now has Unmark option available

### Checklist

- [x] I have written tests which have maintained/increased test coverage.
- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by Vedanth15** [comment]
I tried writing testcases but couldn't finish it. Need help with it.

**Comment by mksavic** [comment]
@Vedanth15 

Updated the description on #194.

**Comment by Vedanth15** [comment]
Closing this PR. Will create a new one with all the necessary changes

**Comment by mksavic** [comment]
@Vedanth15 please delete this branch if you are no longer using it.

**Pull request closed without merging**
