### PR TITLE
63 profile pic

### PR DESCRIPTION
**Pull request by jawooson**
### Description

User Photos uses the django-avatar package, please install before testing. The package allows users to add "avatars" or profile pictures. Right now, only one profile picture can be displayed.

### Testing Directions

```
pip install django-avatar
python manage.py makemigrations
python manage.py migrate
python manage.py pull_seatgeek_data
```
### Misc Notes

* Frontend styling still needs to be done. 
* There is a bug with displaying larger image sizes, so I only displayed the default image size. 
* Adding user images needs to be added to the "Edit Your Profile" button. 
* The "change your avatar" page is part of the templates provided by django-avatar. It does not display the default image, it WILL show the images you upload. 

### Checklist

- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by mksavic** [comment]
@jawooson please write a test case for this.

**Comment by jawooson** [comment]
@Vedanth15 I just git cloned and did the testing process again, I couldn't recreate your error. If you're free I can call and see what you're talking about. 

@mksavic My bad I have two local repos and I think I pushed from the one I was testing. I'll push the merge. I'll also work on test cases, django-avatar has test cases built in, so I'll try to use that for our test. I'm unsure how to test uploaded files that aren't in DB, but I'll figure it out.

**Comment by jawooson** [comment]
@Vedanth15 Oh I misread what you typed. That is NOT a bug, that is the default template provided by django-avatar. It won't show the default photo used, but when you upload a picture, that will be displayed.

**Comment by Vedanth15** [comment]
@jawooson 
Agreed. If you don't mind can you update it in the notes so that anybody else seeing that won't be confused.

**Comment by jawooson** [comment]
@Vedanth15 I included it in the notes!

**Pull request merged**
