### PR TITLE
PR for #6: Implement Messaging

### PR DESCRIPTION
**Pull request by vmoros**
### Description

I implemented messaging. So now, the links on the "it's a match" popup and on the matches page work.

### Testing Directions

```
python manage.py makemigrations
python manage.py migrate
python manage.py pull_seatgeek_data
python manage.py make_users
```

1. Get the code from this PR
1. Make a match, click on the messages link in the match popup, see that it takes you to a messaging page. Send a message.
match message
1. Log in as the other user in the match you just made, go to the matches page, click the messages link, see the message that you just sent as the other person.
message after match

### Miscellaneous Comments

* The chat rooms are based on the squad IDs so when the matching stack is modified to show squads instead of individual users, the messaging page will handle the squads correctly. This will require no or very little modification, depending on how exactly issue #143 is done.

### Checklist

- [x] I have written tests which have maintained/increased test coverage.
- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by jawooson** [comment]
Woo! Awesome, great job. Can you share the showup-nyc-messaging Heroku app with the team?

**Comment by vmoros** [comment]
@mksavic, I added a check in views.py to ensure that one of the squads in the URL is the current user's squad and the other one is a squad that the user has matched with

**Comment by mksavic** [comment]
@vmoros So should the "Message" link on both the popup and `/maches` be working right now? I have a squad {Vik, Vik1, Vik2} and {Vik3, Vik4, Vik5}. They matched but neither of the "Message" links work.

**Comment by vmoros** [comment]
@mksavic, yes, the "Message" link on both the popup and `/matches` should be working right now and are working for me. I just tested both. Please give me more info. Which users are matched, what are their squad IDs, and what are the URLs of the "Message" links?

**Comment by mksavic** [comment]
@vmoros Ok, so I just tested it again and the links work now. But, the divs on `/matches` are messed up:

Screen Shot 2019-11-25 at 12 03 29 PM

In addition, I noticed that once I go to the chat between squad 1 and squad 4, the conversation already existed there:

Screen Shot 2019-11-25 at 12 01 24 PM

Is there an easy way to clear the chat history on the other Heroku instance?

**Comment by vmoros** [comment]
@mksavic, you're right, I messed up the divs. I believe I just fixed it, pls retest.

Regarding the chat history, our current messaging system is weird in the sense that anyone's local chats affect the global chats. I just reset the DB in the messaging Heroku instance so all the chats are gone now.

**Comment by mksavic** [comment]
@vmoros Now the links aren't right aligned:

Screen Shot 2019-11-25 at 3 38 25 PM

**Comment by vmoros** [comment]
@mksavic, check it out now

**Pull request merged**
