### PR TITLE
PR for #82 User Profile: Music Genres

### PR DESCRIPTION
**Pull request by vmoros**
### Description

I added a genres field to the CustomUser model and I updated the Edit Profile page so that a user can specify which genres they like. I also edited the View User Profile page so that you can see which genres the specified user likes.

### Testing Directions

```
python manage.py makemigrations
python manage.py migrate
python manage.py pull_seatgeek_data
```

1. Get the code from this PR
1. Run `pip install django-materializecss-form`
1. Run the Django server, sign up, log in
1. Go to your user profile, click on "Edit Your Profile"
1. Write a nice Bio and click the checkboxes next to your favorite genres
> image
6. Click "Submit", see that you're taken back to your user profile and that your bio and genres are now shown, as desired
> image
7. Sign in as a different user and go to your original user's profile and see that the bio and genres are visible to this other user, as desired

### Miscellaneous Comments

* I'm trying to use descriptive commit messages so please read them. They might pre-emptively answer some of your questions.

### Checklist

- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by Vedanth15** [comment]
I reviewed the PR. I logged in using one user and selected genres, and it looks GREAT. Later I wanted to see if other users who are going to the same concert who could view the profile could also see the genres user2 is interested in. 
image
this popped up. @mksavic @vmoros  Can you please look at it. I created the second user and both the users were going to the same event, when i click the events link from the homepage, this is shown. And also @vmoros  could you please add `pip install django-materializecss-form` in the testing instructions, I know we can figure it out but just so it looks clean.

**Comment by vmoros** [comment]
@Vedanth15 thank you for the thorough review. I'm confident that the error you saw is due to the matching logic, not due to the work on this ticket. If so, it'll be fixed on issue #124. @mksavic, please correct me if I'm wrong.

Regarding people being able to see each other's favorite genres, that does work and it's not dependent on going to the same event. Everyone can see everyone else's profile. This PR didn't touch anything to do with matching. In this pic, I'm logged in as someone else and looking at my profile: 
image

Regarding adding `pip install django-materializecss-form` to the instructions, you're completely right. I'll add it, thank you.

**Comment by Vedanth15** [comment]
@vmoros  Ill try to view user1 profile from user2 or vice-versa and approve the PR if the Genres can be seen.

**Comment by Vedanth15** [comment]
LGTM

**Pull request merged**
