### PR TITLE
PR for #140: Overall Beautification

### PR DESCRIPTION
**Pull request by vmoros**
### Description

I redesigned ShowUp to hopefully look more beautiful.

### Testing Directions

```
python manage.py makemigrations
python manage.py migrate
python manage.py pull_seatgeek_data
```

1. Get the code from this PR
1. Run `pip install django-crispy-forms django-filter`
1. Run the Django server and go to the local server URL
1. See the new homepage
> image
5. Click on "Sign up" and see the new signup page and fill it out
> image
6. Get the email, confirm it, and sign in. See the new login page.
> image
7. See the new home page
> image
8. Go to the events page and see the new design. See that when you scroll down, the filters remain visible. See that for events that you're interested in or going to, the name of the event is now a link to the matching stack for that event.
> image
9. Mark some events as interested and some as going. Mark other users as interested and going to the same events. Go to the homepage and go to the matching stack for an event and see the new design. Test the swiping.
10. Go to your user profile and see the new design.

### Miscellaneous Comments

* I changed pretty much everything so test very thoroughly. I can't write out every single test case so be creative.
* I used the Bootstrap framework. One of its features is that it's responsive to different screen resolutions. Some modern laptops have very high resolutions but mine doesn't so I can't test that. @jawooson and maybe @mksavic, I think yours do so please pay careful attention to the layout of the pages. It all looks good for me but it might look weird for you so please let me know.
* Thanks to @Vedanth15 for help with the signup and matching stack pages.
* @mksavic when you've done issue #139, please change the "Matches" link in the header to point to your new page. 

### Checklist

- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by jawooson** [comment]
This looks AMAZING! Truly a wonderful job. I noticed a very slight issue, the filter side bar in events.html cant be scrolled independently from the rest of the page. To submit the form I need to scroll all the way down the event tile section. Have you noticed it?

**Comment by vmoros** [comment]
@jawooson good catch. I had to make my window pretty small and then I saw the issue you described. I believe I just fixed it by making the filters and the events independently scrollable. Let me know if it's still messed up.

**Comment by vmoros** [comment]
@Vedanth15 absolutely, make any changes you want. I trust you, brother.

Regarding unselecting the filters, I think a good solution would be to change the widgets to a drop-down list with checkboxes. That's what the old events page had and it made sense. The filters right now use the default widgets but I'm sure we can change them.

**Comment by Vedanth15** [comment]
@vmoros  Sounds good.

**Pull request merged**
