### PR TITLE
PR for #210: Can signup with an invalid date of birth

### PR DESCRIPTION
**Pull request by kavinshah**
### Description

Add validations to check if date of birth is a date in the past in signup and settings forms.

### Testing Directions

```
python manage.py makemigrations
python manage.py migrate
python manage.py pull_seatgeek_data
python manage.py make_users
```

1. Signup using date of birth as a date in future. It should throw an error "Value must be {today's date} or earlier"
2. Sign in as a registered user and change the date of birth to a date in futute. It should throw the same error "Value must be {today's date} or earlier"

### Miscellaneous Comments

signup page
settings page

### Checklist

- [X] I have written tests which have maintained/increased test coverage.
- [X] I ran `git merge develop` before submitting this PR.
- [X] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [X] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by kavinshah** [comment]
Used JavaScript to prevent reloading data in case of DOB errors in forms.

**Comment by kavinshah** [comment]
> @kavinshah
> 
> I was able to change Vik's birthday to 01/01/2020.
> 
> Screen Shot 2019-12-09 at 5 11 03 PM

Do you mind mentioning the steps?
AFAIK, it's not possible through the form

**Comment by mksavic** [comment]
@kavinshah 

ScreenRecording2019-12-09at53049

**Comment by kavinshah** [comment]
@mksavic  
did you happen to change your system datetime?

**Comment by mksavic** [comment]
@kavinshah 

No, I didn't.

**Comment by vmoros** [comment]
@mksavic @kavinshah It works in some cases.
image

I think I know why it sometimes doesn't work. The date picker in settings.html says `value = {{user.date_of_birth|date:"Y-m-d"}}` but our test users have blank birthdays so if you view the source of the settings page with a user who has no birthday, you see this:
image

So because the birthday is blank, the id of "dob" is not being correctly given to the date picker, so therefore the JavaScript on line 58 of settings.html is not working.

One solution would be to add birthdays to the test users and make sure that we re-create them on Heroku.

Another solution would be to change the page to work when a user doesn't have a birthday. Maybe an easy way to do that would be to put `value` at the end of the line in settings.html so that id doesn't mess up the id.

**Comment by vmoros** [comment]
@mksavic I just tested the fix that I proposed in my previous comment and it worked so I pushed it. Pls retest.

**Comment by kavinshah** [comment]
> @mksavic I just tested the fix that I proposed in my previous comment and it worked so I pushed it. Pls retest.

@vmoros
I pushed another commit on top your commit by accident. Both do the same thing as you proposed.
Thanks anyways.

**Comment by mksavic** [comment]
@vmoros @kavinshah Is there anyway we can update the model so DOB is a required field in the back end?

**Comment by kavinshah** [comment]
@mksavic yes. by making it not null.
Not sure if it would break any other part of the app since we are basically changing constraints in model without testing it thoroughly.

**Comment by mksavic** [comment]
@kavinshah We have a whole test suite that covers almost entirely all of our code.

**Comment by mksavic** [comment]
@kavinshah If we set `null=False` then we get the following warning/error:

```
You are trying to change the nullable field 'date_of_birth' on customuser to non-nullable without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Ignore for now, and let me handle existing rows with NULL myself (e.g. because you added a RunPython or RunSQL operation to handle NULL values in a previous data migration)
 3) Quit, and let me add a default in models.py
```

So we would have to set a default value if we decided to go with `null=False`. Doesn't seem worth the extra effort since we have to specify a default value anyway.

**Comment by mksavic** [comment]
@kavinshah However, you are only doing client-side checks, which means that a user could still sign up with a future birthday via a manual POST request. Where is your test case for an invalid birthday?

**Comment by kavinshah** [comment]
@mksavic It's mimicking user signup page

**Pull request merged**
