### PR TITLE
111 popup

### PR DESCRIPTION
**Pull request by Vedanth15**
### Description

When 2 users are matched, a popup is shown saying that the user is matched with another user.

### Testing Directions

```
python manage.py makemigrations
python manage.py migrate
python manage.py pull_seatgeek_data
python manage.py make_users
```

1. Create users using make_users (you can create users manually as well)
2. Login into different users and mark events as "interested" or "going" 
3. Open the event stack for the users marked in the previous step from "Home"
4. Create a match between 2 users, a popup will be displayed saying that you are matched with a particular user.

image

### Miscellaneous Comments

Right now we have to press the like/dislike button twice, if you press like button the first time and dislike button the second time an error is popped up and vice-versa. That is not related to this issue.

### Checklist

- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by kavinshah** [comment]
@Vedanth15  please check the boxes in Checklist

**Comment by mksavic** [comment]
@Vedanth15 please write test cases for this.

**Comment by mksavic** [comment]
@Vedanth15 please write a test case for this.

**Comment by Vedanth15** [comment]
@mksavic I see what you are saying. Maybe I should have mentioned it in the comments, Right now we have to click twice on the thumbs up button while swiping on the user. If you click the thumbs up the first time, the form is submitted and then the popup appears, I don't know what happens on the second time you click it. So we see the same user in the event stack again. We have to click to thumbs up again, we have to click our option on the user twice, try clicking thumbs up the first time and thumbs down the second time, or vice-versa, the application is going to crash and an error is displayed. I think this bug you reported is related to the swiping bug i.e we have to swipe them twice. And also if you want to test what I'm saying, try this scenario, Make more than 2 users interested/going to the same event. When the event stack is displayed, don't swipe on the 1st user that is popped up in the event stack, scroll right and swipe on them instead, you should see that they won't be appearing again and we don't have to click it the second time. But if you swipe on the 1st user in the event stack I'm not sure why but you have to click the button again. I believe this is related to bug from matching. I hope this explains your concern.

**Pull request merged**
