### PR TITLE
PR for #217: Set debug to false

### PR DESCRIPTION
**Pull request by vmoros**
### Description

* Set debug to false
* Used whitenoise library to handle static files

### Testing Directions
1. Run `python manage.py collectstatic`
1. I deployed this branch to our develop Heroku instance. So go to https://showup-nyc-develop.herokuapp.com/ and see that everything loads correctly. Our images are shown so that proves that the static files are being handled properly.
1. Go to an incorrect URL on our site such as https://showup-nyc-develop.herokuapp.com/asdfldfdh and see that you get a generic error page instead of the Django debug page, as desired
image

### Miscellaneous Comments

* I followed some of the instructions here: https://devcenter.heroku.com/articles/django-assets

### Checklist

- [x] I have written tests which have maintained/increased test coverage.
- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by mksavic** [comment]
What does the whitenoise library actually do?

**Comment by vmoros** [comment]
> Plz specify whitenoise version in `requirements.txt`.

Got it

> What does the whitenoise library actually do?

It basically takes care of serving static files. I don't know what it does under the hood but I chose to use it because Heroku recommends it here: https://devcenter.heroku.com/articles/django-assets

**Comment by vmoros** [comment]
@mksavic In the screenshot, it looks like the the local CSS files aren't being applied so I think Django isn't seeing any of the static files. So my guess is you need to run `python manage.py collectstatic`. 

If that works, we should add it to the setup script.

**Comment by kavinshah** [comment]
@vmoros  conflicts needs to be resolved

**Comment by vmoros** [comment]
@kavinshah got it

**Pull request merged**
