### PR TITLE
Make test users for Prof & Dan

### PR DESCRIPTION
**Pull request by vmoros**
### Description

* Modified the make_users command to also make test users for Prof & Dan
* Added the make_users command to Procfile so that it'll run on every deployment so that our test users will survive a DB reset
* Added a "forgot password" button to the login page
* Added a template for the password reset page

### Testing Directions

1. Get the code from this PR
1. Delete db.sqlite3
1. Run `python manage.py migrate && python manage.py make_users`
1. See that accounts are made for Prof & Dan, along with the usual test accounts. This simulates what will happen when we deploy after a DB reset.
image
1. Run `python manage.py make_users` again. See that no new users are created because the command realizes that the users already exist. This simulates what will happen when we deploy without a DB reset.
image
1. Sign in as Prof with email gcivil@nyu.edu and password heyhey123. See that it works.
1. Sign in as Dan with email dgopstein@nyu.edu and password heyhey123. See that it works.
1. Log out, click the "forgot password" link on the login page, put in your email address (assuming you already have an account, create one if not), see that you get an email, click the link in it, see that you can reset your password.

### Miscellaneous Comments

* We can't truly test Procfile locally because it only applies to Heroku deployments, and the Heroku environment is different from our local ones. But as noted in the testing steps, we can try to simulate what Procfile will do in various scenarios.

### Checklist

- [x] I have written tests which have maintained/increased test coverage.
- [x] I ran `git merge develop` before submitting this PR.
- [x] I understand that I may have to run `git merge develop` again after submitting this PR since new changes may have been pulled into `develop`.
- [x] I understand that it is MY responsibility to make sure that this PR does not have any conflicts.

### CODE REVIEW

**Comment by Vedanth15** [comment]
@vmoros  Please check the boxes.

**Comment by vmoros** [comment]
> I don't think we should upload prof's avatar while making the users

I agree and my script doesn't do that. Look at the changes in this PR, none of them have anything to do with a picture for Professor.

If you look at the URL of his picture, you'll see that it's at gravatar.com, not in our local media folder where the other avatars go. I think what happened is he used gravatar.com to associate an avatar with his email address and django-avatar is using that. Put gcivil@nyu.edu into [this website](https://en.gravatar.com/site/check/) and you'll see his avatar.

The [django-avatar documentation](https://django-avatar.readthedocs.io/en/latest/) says
> It has the ability to default to avatars provided by third party services (like Gravatar or Facebook) if no avatar is found for a certain user.

So I'm pretty sure that explains both things you pointed out.

**Comment by Vedanth15** [comment]
@vmoros im sorry I thought you put the picture because it looked great. My bad didn't review the code. I should have my bad. django-avatars is crazy lol.

**Comment by jawooson** [comment]
Its funny he has a gravatar already. Lumpy Goops Tickle Moths!

**Comment by vmoros** [comment]
I just fixed a merge conflict with make_users that was introduced by PR #168. @Vedanth15, your approval was from before that so can you please re-test it or maybe someone else can test it.

**Pull request merged**
